name: Go

on:
  push:
    branches: 
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - if: startsWith(matrix.os,'ubuntu')
        name: Set up LibGL, Mesa & X11 libraries
        run: |
          sudo apt-get --allow-releaseinfo-change update
          sudo apt-get install -y libgtk-3-dev libasound2-dev libxxf86vm-dev

      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Build
        run: |
          chmod +x build.sh
          ./build.sh
      - name: Test
        run: go test -race -v ./...

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          path: PortableBuildTools*
          name: ${{ github.run_number }}
