name: Go

on:
  push:
    branches: 
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: "stable"
          cache-dependency-path: project/go/go.sum

      - name: Build
        working-directory: project/go
        run: |
          chmod +x build.sh
          ./build.sh
      - name: Test
        working-directory: project/go
        run: go test -race -v ./...

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          path: project/go/PortableBuildTools*
          name: ${{ github.run_number }}
